// this is a read only file generated by mustache/handle-rates.
export let contractsToProxies = new Map<string, string>();
contractsToProxies.set(
  '0xb2397a9247323ca2f207139401e2d55748a1ba78', // BTC / USD
  '0x81AE7F8fF54070C52f0eB4EB5b8890e1506AA4f4',
);
contractsToProxies.set(
  '0xeef539668bf125b29cd109bdba864c9bf6247ac7', // ETH / USD
  '0xCb7895bDC70A1a1Dce69b689FD7e43A627475A06',
);
contractsToProxies.set(
  '0x23b3d7a59b2b79d390c53f0745e342249c040802', // LINK / USD
  '0xb37aA79EBc31B93864Bff2d5390b385bE482897b',
);
contractsToProxies.set(
  '0xd98bef7fd4c528d6fe97acb6c322b1531e40c992', // SNX / USD
  '0xd9E9047ED2d6e2130395a2Fe08033e756CC7e288',
);
contractsToProxies.set(
  '0x2f42ee625893d93e2607a37cfc932d8c7f6043a9', // DEFI / USD
  '0x943525fA16039d7Bcc4CAB020a7E23115DC20736',
);
contractsToProxies.set(
  '0x6cbe4f3c316d8d24946166c0aeeaf346c3fde487', // UNI / USD
  '0xbac904786e476632e75fC6214C797fA80cce9311',
);
contractsToProxies.set(
  '0x8645eb75898a1e049b624369444600061d46b801', // AAVE / USD
  '0xc051eCEaFd546e0Eb915a97F4D0643BEd7F98a11',
);
contractsToProxies.set(
  '0xcc67978a452588ded1cc70743eb6524f3a73ca49', // TSLA / USD
  '0x4bFa8c47f9521B0E8f48C14b3288c2258c538C49',
);
// this is a read only file generated by mustache/handle-rates.
