// this is a read only file generated by the codegen command.
export let escrowContracts = new Map<string, string>();
escrowContracts.set('rewardEscrow-mainnet', '0xb671f2210b1f6621a2607ea63e6b2dc3e2464d1f');
escrowContracts.set('escrow-mainnet', '0x971e78e0c92392a4e39099835cf7e6ab535b2227');
escrowContracts.set('rewardEscrow-kovan', '0x8c6680412e914932a9abc02b6c7cbf690e583afa');
escrowContracts.set('escrow-kovan', '0x548c18a49a66ad1238e17824c18b0b9be35fb604');
escrowContracts.set('rewardEscrow-optimism-kovan', '0x9952e42ff92149f48b3b7dee3f921a6dd106f79f');
escrowContracts.set('escrow-optimism-kovan', '0xf545e539788afeaa665b7d79568e306e37ef05cc');
escrowContracts.set('rewardEscrow-optimism', '0xd32138018210eda0028240638f35b70ecc0d8c22');
escrowContracts.set('escrow-optimism', '0x06c6d063896ac733673c4474e44d9268f2402a55');
// this is a read only file generated by the codegen command.
