/* eslint-disable @typescript-eslint/no-var-requires */
'use strict';

const fs = require('fs');
const Mustache = require('mustache');
const program = require('commander');
const contracts = require('./subgraphs/synthetix/mustache/contracts');
const template = require('./subgraphs/synthetix/mustache/yaml');

const networks = ['kovan', 'optimism', 'optimism-kovan', 'mainnet'];

program
  .command('init-subgraph')
  .description('Creates the necessary yaml and helper files for any supported synthetix subgraph')
  .option(
    '-s, --subgraph <value>',
    'defaults to synthetix but can be named after any folder under the main level subgraphs folder',
    'synthetix',
  )
  .action(({ subgraph }) =>
    networks.map(network =>
      fs.writeFileSync(
        `./subgraphs/${subgraph}/autoGeneratedYaml/${subgraph}-${network}.yaml`,
        Mustache.render(template(network), contracts),
      ),
    ),
  );

program.parse(process.argv);
