// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToProxies = new Map<string, string>();
contractsToProxies.set(
  '0x05cf62c4ba0ccea3da680f9a8744ac51116d6231', // AggregatorAUD
  '0x77F9710E7d0A19669A13c055F62cd80d313dF022'
);
contractsToProxies.set(
  '0x25fa978ea1a7dc9bdc33a2959b9053eae57169b5', // AggregatorEUR
  '0xb49f677943BC038e9857d61E7d053CaA2C1734C1'
);
contractsToProxies.set(
  '0x02d5c618dbc591544b19d0bf13543c0728a3c4ec', // AggregatorCHF
  '0x449d117117838fFA61263B61dA6301AA2a88B13A'
);
contractsToProxies.set(
  '0x151445852b0cfdf6a4cc81440f2af99176e8ad08', // AggregatorGBP
  '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5'
);
contractsToProxies.set(
  '0xe1407bfaa6b5965bad1c9f38316a3b655a09d8a6', // AggregatorJPY
  '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3'
);
contractsToProxies.set(
  '0x8946a183bfafa95becf57c5e08fe5b7654d2807b', // AggregatorXAG
  '0x379589227b15F1a12195D3f2d90bBc9F31f95235'
);
contractsToProxies.set(
  '0xafce0c7b7fe3425adb3871eae5c0ec6d93e01935', // AggregatorXAU
  '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6'
);
contractsToProxies.set(
  '0x16924ae9c2ac6cdbc9d6bb16fafcd38bed560936', // AggregatorFTSE
  '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c'
);
contractsToProxies.set(
  '0x3f6e09a4ec3811765f5b2ad15c0279910dbb2c04', // AggregatorN225
  '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980'
);
contractsToProxies.set(
  '0xd3ce735cdc708d9607cfbc6c3429861625132cb4', // AggregatorSNX
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0xf79d6afbb6da890132f9d7c355e3015f15f3406f', // AggregatorETH
  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
);
contractsToProxies.set(
  '0x80eeb41e2a86d4ae9903a3860dd643dad2d1a853', // AggregatorCOMP
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x45e9fee61185e213c37fc14d18e44ef9262e10db', // AggregatorKNC
  '0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc'
);
contractsToProxies.set(
  '0x2408935efe60f092b442a8755f7572edb9cf971e', // AggregatorLEND
  '0x4aB81192BB75474Cf203B56c36D6a13623270A67'
);
contractsToProxies.set(
  '0x353f61f39a17e56ca413f4559b8cd3b6a252ffc8', // AggregatorREN
  '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01'
);
contractsToProxies.set(
  '0xf5fff180082d6017036b771ba883025c654bc935', // AggregatorBTC
  '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
);
contractsToProxies.set(
  '0x0821f21f21c325ae39557ca83b6b4df525495d06', // AggregatorBNB
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
contractsToProxies.set(
  '0x28e0fd8e05c14034cba95c6bf3394d1b106f7ed8', // AggregatorTRX
  '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25'
);
contractsToProxies.set(
  '0x52d674c76e91c50a0190de77da1fad67d859a569', // AggregatorXTZ
  '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F'
);
contractsToProxies.set(
  '0x570985649832b51786a181d57babe012be1c09a4', // AggregatorXRP
  '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12'
);
contractsToProxies.set(
  '0xc6ee0d4943dc43bd462145aa6ac95e9c0c8b462f', // AggregatorLTC
  '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B'
);
contractsToProxies.set(
  '0x32dbd3214ac75223e27e575c53944307914f7a90', // AggregatorLINK
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0x740be5e8fe30bd2bf664822154b520eae0c565b0', // AggregatorEOS
  '0x10a43289895eAff840E8d45995BBa89f9115ECEe'
);
contractsToProxies.set(
  '0x6a6527d91ddae0a259cc09dad311b3455cdc1fbd', // AggregatorBCH
  '0x9F0F69428F923D6c95B781F89E165C9b2df9789D'
);
contractsToProxies.set(
  '0xe2c9aea66ed352c33f9c7d8e824b7cac206b0b72', // AggregatorETC
  '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
);
contractsToProxies.set(
  '0xd9d35a82d4dd43be7cfc524ebf5cd00c92c48ebc', // AggregatorDASH
  '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912'
);
contractsToProxies.set(
  '0xd1e850d6afb6c27a3d66a223f6566f0426a6e13b', // AggregatorXMR
  '0xFA66458Cce7Dd15D8650015c4fce4D278271618F'
);
contractsToProxies.set(
  '0xf11bf075f0b2b8d8442ab99c44362f1353d40b44', // AggregatorADA
  '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55'
);
contractsToProxies.set(
  '0x46bb139f23b01fef37cb95ae56274804bc3b3e86', // AggregatorCEX
  '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2'
);
contractsToProxies.set(
  '0x7ae7781c7f3a5182596d161e037e6db8e36328ef', // AggregatorDEFI
  '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87'
);
contractsToProxies.set(
  '0x06a7689149cf04dacfde555d1e1ead7dd7370316', // AggregatorXAU_3
  '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6'
);
contractsToProxies.set(
  '0xf320e19b2ed82f1b226b006cd43fe600fea56615', // AggregatorXAG_3
  '0x379589227b15F1a12195D3f2d90bBc9F31f95235'
);
contractsToProxies.set(
  '0x8cde021f0bfa5f82610e8ce46493cf66ac04af53', // AggregatorLINK_3
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0xf570deefff684d964dc3e15e1f9414283e3f7419', // AggregatorBTC_3
  '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
);
contractsToProxies.set(
  '0x3a33c0efd0eb8fd38a6e1904df1e32f95f67616b', // AggregatorAUD_3
  '0x77F9710E7d0A19669A13c055F62cd80d313dF022'
);
contractsToProxies.set(
  '0x8f71c9c583248a11cacbbc8fd0d5dfa483d3b109', // AggregatorEUR_3
  '0xb49f677943BC038e9857d61E7d053CaA2C1734C1'
);
contractsToProxies.set(
  '0x744704c31a2e46ad60c7cdf0212933b4c4c2c9ec', // AggregatorBCH_3
  '0x9F0F69428F923D6c95B781F89E165C9b2df9789D'
);
contractsToProxies.set(
  '0x7c9ca5adcba43d968d9e0ddca16293d66c07482d', // AggregatorEOS_3
  '0x10a43289895eAff840E8d45995BBa89f9115ECEe'
);
contractsToProxies.set(
  '0x90888cddad598570c6edc443eee9aadb63cda3c4', // AggregatorBNB_3
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
contractsToProxies.set(
  '0xf94800e6e36b0dc860f6f31e7cdf1086099e8c0e', // AggregatorADA_3
  '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55'
);
contractsToProxies.set(
  '0xd286af227b7b0695387e279b9956540818b1dc2a', // AggregatorREN_3
  '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01'
);
contractsToProxies.set(
  '0x0227fb846b48e209d56d79b0a3109fda561db821', // AggregatorLEND_3
  '0x4aB81192BB75474Cf203B56c36D6a13623270A67'
);
contractsToProxies.set(
  '0xa811ff165b082c0507ce9a5a660fb3d7eeecb88a', // AggregatorKNC_3
  '0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc'
);
contractsToProxies.set(
  '0xc8db8d5869510bb1fcd3bd7c7624c1b49c652ef8', // AggregatorSNX_3
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0x1fb0b88eaf51420c14b67256ab7dae1de6e116cb', // AggregatorDASH_3
  '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912'
);
contractsToProxies.set(
  '0x41306eb5fc11a68c284c19ba3b9510c0252e0a34', // AggregatorETC_3
  '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
);
contractsToProxies.set(
  '0x3f2d1ff4930318b5a7c301e1bf7e703dcf6d83e3', // AggregatorLTC_3
  '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B'
);
contractsToProxies.set(
  '0x38cb8642a0fc558918fced939450d689d0e5a7be', // AggregatorXMR_3
  '0xFA66458Cce7Dd15D8650015c4fce4D278271618F'
);
contractsToProxies.set(
  '0x75ed2f61837c3d9ef1bf0af4db84664dc6fe56bc', // AggregatorXRP_3
  '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12'
);
contractsToProxies.set(
  '0x4d35fe9c85233a8e00ae2d3c0d912a45bc781025', // AggregatorTRX_3
  '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25'
);
contractsToProxies.set(
  '0x7391bb54a24719da7dd81c2e5176cf954d7f7635', // AggregatorXTZ_3
  '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F'
);
contractsToProxies.set(
  '0x150631a2e822d3ed7d46df9a270ce7134a16de89', // AggregatorCOMP_3
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x25367741a23464b41b4ab978bd8092d56a3590c0', // AggregatorDEFI_3
  '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87'
);
contractsToProxies.set(
  '0xbc66d51898dd2efa3c214c87d4645c0478ccbc95', // AggregatorCEX_3
  '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2'
);
contractsToProxies.set(
  '0x00c7a37b03690fb9f41b5c5af8131735c7275446', // AggregatorETH_3
  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
);
contractsToProxies.set(
  '0xdf005cad29aac8b1170960807f99b62aaed1bb0a', // AggregatorCHF_3
  '0x449d117117838fFA61263B61dA6301AA2a88B13A'
);
contractsToProxies.set(
  '0x87cfea02c8322653a7335c6f72be19ce54ecbfb5', // AggregatorJPY_3
  '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3'
);
contractsToProxies.set(
  '0x3a6e27b663593e34a7fb80ba9544d9e8babdf001', // AggregatorGBP_3
  '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5'
);
contractsToProxies.set(
  '0xc95b41df94f3890122b2bcef9005afde17773db2', // AggregatorFTSE_3
  '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c'
);
contractsToProxies.set(
  '0x4fa0655c09e0b5b2f50f1bd861b2d9bc63ccbbcb', // AggregatorN225_3
  '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980'
);
contractsToProxies.set(
  '0xf0f201fdb77a5ecd065cdbd69850f3f6694b2bef', // AggregatorOIL_3
  '0xb70ba475F1a6b5396e46d9b2a5f7081080Dc9d09'
);
contractsToProxies.set(
  '0xf2d87e37ea1e54c7aa913d2447a5f69f61c114cf', // AggregatorAAVE_3
  '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9'
);
contractsToProxies.set(
  '0x8640798469204dbbad5842f8688b152c510f7777', // AggregatorDOT_3
  '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734'
);
contractsToProxies.set(
  '0x5b0e9ff11aae806067787d380967900551919c0d', // AggregatorUNI_3
  '0x553303d460EE0afB37EdFf9bE42922D8FF63220e'
);
contractsToProxies.set(
  '0x2b89ec8b7d018ca574e844edff24c17c6bb3e3a1', // AggregatorFIL_3
  '0x1A31D42149e82Eb99777f903C08A2E41A00085d3'
);
contractsToProxies.set(
  '0xaec0d77fdd6a2a34ec3eaf915260496ae27f9d25', // AggregatorYFI_3
  '0xA027702dbb89fbd58938e4324ac03B58d812b0E1'
);
contractsToProxies.set(
  '0x2747254824f1731e016352e3267735fd9a6331c0', // AggregatorOIL_3_1
  '0xf3584F4dd3b467e73C2339EfD008665a70A4185c'
);
contractsToProxies.set(
  '0x21cbd7098bf18f293fbf5451be2fc968eaa1e072', // AggregatorTesla_3
  '0x1ceDaaB50936881B3e449e47e40A2cDAF5576A4a'
);
contractsToProxies.set(
  '0xf4ebc177fbbd15874c08cccbc3dd383ee1a24a9d', // AggregatorLINK_4
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0xf6eeca2fd1ace8c17389b119de983e9fd9a8ee8f', // AggregatorXTZ_4
  '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F'
);
contractsToProxies.set(
  '0x7c8719f3683585a242a67c73f6f3c98362004da4', // AggregatorCHF_4
  '0x449d117117838fFA61263B61dA6301AA2a88B13A'
);
contractsToProxies.set(
  '0x02f878a94a1ae1b15705acd65b5519a46fe3517e', // AggregatorEUR_4
  '0xb49f677943BC038e9857d61E7d053CaA2C1734C1'
);
contractsToProxies.set(
  '0x01a1f73b1f4726eb6eb189ffa5cbb91af8e14025', // AggregatorJPY_4
  '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3'
);
contractsToProxies.set(
  '0x568b8fd03992f56bf240958d22f5a6fcf7bd850b', // AggregatorGBP_4
  '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5'
);
contractsToProxies.set(
  '0x7f7b323291c052de18926396176d384c4a8e19e2', // AggregatorAUD_4
  '0x77F9710E7d0A19669A13c055F62cd80d313dF022'
);
contractsToProxies.set(
  '0xdeb43523e2857b7ec29d078c77b73709d958c62f', // AggregatorXAG_4
  '0x379589227b15F1a12195D3f2d90bBc9F31f95235'
);
contractsToProxies.set(
  '0xea5f70faa03f5c30b96029635c8d431d1a3cd1b8', // AggregatorXAU_4
  '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6'
);
contractsToProxies.set(
  '0xe4b36bbc01ead5a378d4cb088604bfe5ab2cefe3', // AggregatorYFI_4
  '0xA027702dbb89fbd58938e4324ac03B58d812b0E1'
);
contractsToProxies.set(
  '0xc45ebd0f901ba6b2b8c7e70b717778f055ef5e6d', // AggregatorBNB_5
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
contractsToProxies.set(
  '0xdd860a2ad1b6ebdf2b17d7d01d65a7be3926be84', // AggregatorTRX_4
  '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25'
);
contractsToProxies.set(
  '0x3d0bb55d0d2f255d7a0eab8a53a91b3369728e36', // AggregatorREN_4
  '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01'
);
contractsToProxies.set(
  '0xbc60258f775683ea28048030806ad3a80c4a33ae', // AggregatorKNC_4
  '0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc'
);
contractsToProxies.set(
  '0x4d839a486ec0b1c9b0d9e9d397993ba5b150cb34', // AggregatorXRP_4
  '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12'
);
contractsToProxies.set(
  '0xd054be48ae13a89a82744373f647a755df7cae17', // AggregatorBCH_4
  '0x9F0F69428F923D6c95B781F89E165C9b2df9789D'
);
contractsToProxies.set(
  '0xea7c55976844396f3bd4c89f66988b8b5be5e96a', // AggregatorEOS_4
  '0x10a43289895eAff840E8d45995BBa89f9115ECEe'
);
contractsToProxies.set(
  '0x56658e9312218923b4aeb3727304b6060ab69e8f', // AggregatorCOMP_4
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x7002049fdca829ed7082efa03860b078ad4b5efe', // AggregatorDASH_4
  '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912'
);
contractsToProxies.set(
  '0xfe3d09d8bad5da65e0160cf0cb53f6115fb6ea8b', // AggregatorLTC_4
  '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B'
);
contractsToProxies.set(
  '0xf09828103d306f50af7e3132adb6def77c6d96f7', // AggregatorXMR_4
  '0xFA66458Cce7Dd15D8650015c4fce4D278271618F'
);
contractsToProxies.set(
  '0x06ce8be8729b6ba18dd3416e3c223a5d4db5e755', // AggregatorSNX_4
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0x0c7907d97b7f708ecda1a0b3124d32cd8b1e3920', // AggregatorETC_4
  '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
);
contractsToProxies.set(
  '0xbe4274dfb7801948e2cc2a913744e9498ddc8d20', // AggregatorDOT_4
  '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734'
);
contractsToProxies.set(
  '0xd6947812a94e323608dcd4f84b835a586baf21eb', // AggregatorUNI_4
  '0x553303d460EE0afB37EdFf9bE42922D8FF63220e'
);
contractsToProxies.set(
  '0xc8f8d8d5ab0f874f00d74b1ef448151631bc3473', // AggregatorAAVE_4
  '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9'
);
contractsToProxies.set(
  '0xb4dd24b6b98ea9c18e2196e166f17b15f77b0a07', // AggregatorFIL_4
  '0x1A31D42149e82Eb99777f903C08A2E41A00085d3'
);
contractsToProxies.set(
  '0xbc3c868763b7c15d0ce527af455041919e9c07b1', // AggregatorADA_4
  '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55'
);
contractsToProxies.set(
  '0xb3bcb06bbf2413d88c46cabf40e4ba54e1189c86', // AggregatorCEX_4
  '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2'
);
contractsToProxies.set(
  '0x04cde3a52a72c2d56923c94242bfc15a8d9d9e36', // AggregatorDEFI_4
  '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87'
);
contractsToProxies.set(
  '0x5306b60fe2598d268732ffe1fa37065931de127c', // AggregatorFTSE_4
  '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c'
);
contractsToProxies.set(
  '0x40c0bc7bfb90a29426121ba133a9352b84c5f2cf', // AggregatorN225_4
  '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980'
);
contractsToProxies.set(
  '0xbd11bc57fc140614190cabc1b4c316aba220bae4', // AggregatorLINK_5
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0x256b6e10c153b49ac7800e2603167026f75eb765', // AggregatorKRW
  '0x01435677FB11763550905594A16B645847C1d0F3'
);
contractsToProxies.set(
  '0x86e345d4113e1105053a81240c75b56b437da6ef', // AggregatorKRW_2
  '0x01435677FB11763550905594A16B645847C1d0F3'
);
contractsToProxies.set(
  '0x0deaf87519d434dcf74551b2e907af18d2304946', // AggregatorOIL_4
  '0xf3584F4dd3b467e73C2339EfD008665a70A4185c'
);
contractsToProxies.set(
  '0x404be42e956990b1295cf2405f0945b942b32055', // AggregatorTesla_4
  '0x1ceDaaB50936881B3e449e47e40A2cDAF5576A4a'
);
contractsToProxies.set(
  '0x6e450877fcbfa655722ed5df6902c979c099a852', // AggregatorAMZN
  '0x8994115d287207144236c13Be5E2bDbf6357D9Fd'
);
contractsToProxies.set(
  '0x43cbd8be1ebd180107f1e0e8facd80941f0c5075', // AggregatorGOOG
  '0x36D39936BeA501755921beB5A382a88179070219'
);
contractsToProxies.set(
  '0xefcbea1e97888793896458dc79fce7ad36a70fef', // AggregatorNFLX
  '0x67C2e69c5272B94AF3C90683a9947C39Dc605ddE'
);
contractsToProxies.set(
  '0xc697fca98f961169b53e80b718155b55fc1a17d5', // AggregatorAAPL
  '0x139C8512Cde1778e9b9a8e721ce1aEbd4dD43587'
);
contractsToProxies.set(
  '0xd3fcd40153e56110e6eeae13e12530e26c9cb4fd', // AggregatorETH_4
  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
);
contractsToProxies.set(
  '0x7104ac4abcecf1680f933b04c214b0c491d43ecc', // AggregatorBTC_4
  '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
