// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToProxies = new Map<string, string>();
contractsToProxies.set(
  '0x05cf62c4ba0ccea3da680f9a8744ac51116d6231', // AggregatorAUD
  '0x77F9710E7d0A19669A13c055F62cd80d313dF022'
);
contractsToProxies.set(
  '0x25fa978ea1a7dc9bdc33a2959b9053eae57169b5', // AggregatorEUR
  '0xb49f677943BC038e9857d61E7d053CaA2C1734C1'
);
contractsToProxies.set(
  '0x02d5c618dbc591544b19d0bf13543c0728a3c4ec', // AggregatorCHF
  '0x449d117117838fFA61263B61dA6301AA2a88B13A'
);
contractsToProxies.set(
  '0x151445852b0cfdf6a4cc81440f2af99176e8ad08', // AggregatorGBP
  '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5'
);
contractsToProxies.set(
  '0xe1407bfaa6b5965bad1c9f38316a3b655a09d8a6', // AggregatorJPY
  '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3'
);
contractsToProxies.set(
  '0x8946a183bfafa95becf57c5e08fe5b7654d2807b', // AggregatorXAG
  '0x379589227b15F1a12195D3f2d90bBc9F31f95235'
);
contractsToProxies.set(
  '0xafce0c7b7fe3425adb3871eae5c0ec6d93e01935', // AggregatorXAU
  '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6'
);
contractsToProxies.set(
  '0x16924ae9c2ac6cdbc9d6bb16fafcd38bed560936', // AggregatorFTSE
  '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c'
);
contractsToProxies.set(
  '0x3f6e09a4ec3811765f5b2ad15c0279910dbb2c04', // AggregatorN225
  '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980'
);
contractsToProxies.set(
  '0xd3ce735cdc708d9607cfbc6c3429861625132cb4', // AggregatorSNX
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0xf79d6afbb6da890132f9d7c355e3015f15f3406f', // AggregatorETH
  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
);
contractsToProxies.set(
  '0x80eeb41e2a86d4ae9903a3860dd643dad2d1a853', // AggregatorCOMP
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x45e9fee61185e213c37fc14d18e44ef9262e10db', // AggregatorKNC
  '0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc'
);
contractsToProxies.set(
  '0x2408935efe60f092b442a8755f7572edb9cf971e', // AggregatorLEND
  '0x4aB81192BB75474Cf203B56c36D6a13623270A67'
);
contractsToProxies.set(
  '0x353f61f39a17e56ca413f4559b8cd3b6a252ffc8', // AggregatorREN
  '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01'
);
contractsToProxies.set(
  '0xf5fff180082d6017036b771ba883025c654bc935', // AggregatorBTC
  '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
);
contractsToProxies.set(
  '0x0821f21f21c325ae39557ca83b6b4df525495d06', // AggregatorBNB
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
contractsToProxies.set(
  '0x28e0fd8e05c14034cba95c6bf3394d1b106f7ed8', // AggregatorTRX
  '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25'
);
contractsToProxies.set(
  '0x52d674c76e91c50a0190de77da1fad67d859a569', // AggregatorXTZ
  '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F'
);
contractsToProxies.set(
  '0x570985649832b51786a181d57babe012be1c09a4', // AggregatorXRP
  '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12'
);
contractsToProxies.set(
  '0xc6ee0d4943dc43bd462145aa6ac95e9c0c8b462f', // AggregatorLTC
  '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B'
);
contractsToProxies.set(
  '0x32dbd3214ac75223e27e575c53944307914f7a90', // AggregatorLINK
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0x740be5e8fe30bd2bf664822154b520eae0c565b0', // AggregatorEOS
  '0x10a43289895eAff840E8d45995BBa89f9115ECEe'
);
contractsToProxies.set(
  '0x6a6527d91ddae0a259cc09dad311b3455cdc1fbd', // AggregatorBCH
  '0x9F0F69428F923D6c95B781F89E165C9b2df9789D'
);
contractsToProxies.set(
  '0xe2c9aea66ed352c33f9c7d8e824b7cac206b0b72', // AggregatorETC
  '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
);
contractsToProxies.set(
  '0xd9d35a82d4dd43be7cfc524ebf5cd00c92c48ebc', // AggregatorDASH
  '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912'
);
contractsToProxies.set(
  '0xd1e850d6afb6c27a3d66a223f6566f0426a6e13b', // AggregatorXMR
  '0xFA66458Cce7Dd15D8650015c4fce4D278271618F'
);
contractsToProxies.set(
  '0xf11bf075f0b2b8d8442ab99c44362f1353d40b44', // AggregatorADA
  '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55'
);
contractsToProxies.set(
  '0x46bb139f23b01fef37cb95ae56274804bc3b3e86', // AggregatorCEX
  '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2'
);
contractsToProxies.set(
  '0x7ae7781c7f3a5182596d161e037e6db8e36328ef', // AggregatorDEFI
  '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87'
);
contractsToProxies.set(
  '0x06A7689149cf04DacFDE555d1e1EAD7dD7370316', // AggregatorXAU_3
  '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6'
);
contractsToProxies.set(
  '0xF320E19B2ED82F1B226b006cD43FE600FEA56615', // AggregatorXAG_3
  '0x379589227b15F1a12195D3f2d90bBc9F31f95235'
);
contractsToProxies.set(
  '0x8cDE021F0BfA5f82610e8cE46493cF66AC04Af53', // AggregatorLINK_3
  '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'
);
contractsToProxies.set(
  '0xF570deEffF684D964dc3E15E1F9414283E3f7419', // AggregatorBTC_3
  '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
);
contractsToProxies.set(
  '0x3A33c0eFD0EB8fd38a6E1904dF1E32f95F67616b', // AggregatorAUD_3
  '0x77F9710E7d0A19669A13c055F62cd80d313dF022'
);
contractsToProxies.set(
  '0x8f71c9c583248A11CAcBbC8FD0D5dFa483D3b109', // AggregatorEUR_3
  '0xb49f677943BC038e9857d61E7d053CaA2C1734C1'
);
contractsToProxies.set(
  '0x744704c31a2E46AD60c7CDf0212933B4c4c2c9eC', // AggregatorBCH_3
  '0x9F0F69428F923D6c95B781F89E165C9b2df9789D'
);
contractsToProxies.set(
  '0x7C9Ca5AdcBa43D968D9e0dDcA16293D66c07482D', // AggregatorEOS_3
  '0x10a43289895eAff840E8d45995BBa89f9115ECEe'
);
contractsToProxies.set(
  '0x90888CDDaD598570c6eDC443eee9aaDB63cDA3C4', // AggregatorBNB_3
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
contractsToProxies.set(
  '0xf94800E6e36b0dc860F6f31e7cDf1086099E8c0E', // AggregatorADA_3
  '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55'
);
contractsToProxies.set(
  '0xD286AF227B7b0695387E279B9956540818B1dc2a', // AggregatorREN_3
  '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01'
);
contractsToProxies.set(
  '0x0227fb846b48e209d56D79b0A3109FdA561db821', // AggregatorLEND_3
  '0x4aB81192BB75474Cf203B56c36D6a13623270A67'
);
contractsToProxies.set(
  '0xa811Ff165b082c0507Ce9a5a660Fb3D7eEeCb88A', // AggregatorKNC_3
  '0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc'
);
contractsToProxies.set(
  '0xC8DB8d5869510Bb1FCd3Bd7C7624c1b49c652ef8', // AggregatorSNX_3
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0x1fB0b88eaF51420c14B67256Ab7DaE1de6e116cb', // AggregatorDASH_3
  '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912'
);
contractsToProxies.set(
  '0x41306Eb5fC11A68C284c19Ba3B9510c0252E0a34', // AggregatorETC_3
  '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
);
contractsToProxies.set(
  '0x3F2d1Ff4930318B5a7c301E1bf7e703DcF6D83E3', // AggregatorLTC_3
  '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B'
);
contractsToProxies.set(
  '0x38cB8642A0FC558918fCed939450D689d0E5a7Be', // AggregatorXMR_3
  '0xFA66458Cce7Dd15D8650015c4fce4D278271618F'
);
contractsToProxies.set(
  '0x75Ed2f61837c3D9Ef1BF0af4DB84664DC6fe56bC', // AggregatorXRP_3
  '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12'
);
contractsToProxies.set(
  '0x4D35fE9C85233a8E00aE2d3C0d912a45Bc781025', // AggregatorTRX_3
  '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25'
);
contractsToProxies.set(
  '0x7391BB54a24719DA7DD81c2E5176cf954D7f7635', // AggregatorXTZ_3
  '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F'
);
contractsToProxies.set(
  '0x150631a2e822d3ed7D46df9A270ce7134a16De89', // AggregatorCOMP_3
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x25367741a23464b41B4aB978Bd8092d56a3590C0', // AggregatorDEFI_3
  '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87'
);
contractsToProxies.set(
  '0xBC66D51898dd2EFA3C214C87d4645C0478Ccbc95', // AggregatorCEX_3
  '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2'
);
contractsToProxies.set(
  '0x00c7A37B03690fb9f41b5C5AF8131735C7275446', // AggregatorETH_3
  '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
);
contractsToProxies.set(
  '0xdf005CaD29AAC8b1170960807f99B62aaeD1bb0a', // AggregatorCHF_3
  '0x449d117117838fFA61263B61dA6301AA2a88B13A'
);
contractsToProxies.set(
  '0x87CFEA02C8322653a7335C6f72Be19ce54ECbFb5', // AggregatorJPY_3
  '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3'
);
contractsToProxies.set(
  '0x3a6e27b663593E34a7FB80bA9544d9E8BAbdF001', // AggregatorGBP_3
  '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5'
);
contractsToProxies.set(
  '0xc95B41df94F3890122B2bcEf9005AFDe17773dB2', // AggregatorFTSE_3
  '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c'
);
contractsToProxies.set(
  '0x4Fa0655c09E0b5B2F50F1bd861B2d9BC63ccBBCB', // AggregatorNIKKEI_3
  '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980'
);
contractsToProxies.set(
  '0xF0f201FDB77a5eCd065CdbD69850F3f6694B2BEf', // AggregatorOIL_3
  '0xb70ba475F1a6b5396e46d9b2a5f7081080Dc9d09'
);
contractsToProxies.set(
  '0xF2d87E37EA1e54c7Aa913d2447A5f69f61C114Cf', // AggregatorAAVE_3
  '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9'
);
contractsToProxies.set(
  '0x8640798469204DBbAd5842f8688B152c510F7777', // AggregatorDOT_3
  '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734'
);
contractsToProxies.set(
  '0x5B0e9Ff11aae806067787d380967900551919c0D', // AggregatorUNI_3
  '0x553303d460EE0afB37EdFf9bE42922D8FF63220e'
);
contractsToProxies.set(
  '0x2B89EC8B7d018CA574E844EdFF24c17c6BB3E3a1', // AggregatorFIL_3
  '0x1A31D42149e82Eb99777f903C08A2E41A00085d3'
);
contractsToProxies.set(
  '0xAec0D77fdD6a2a34EC3eaF915260496Ae27f9D25', // AggregatorYFI_3
  '0xA027702dbb89fbd58938e4324ac03B58d812b0E1'
);
contractsToProxies.set(
  '0x2747254824f1731e016352e3267735fd9a6331C0', // AggregatorOIL_3_1
  '0xf3584F4dd3b467e73C2339EfD008665a70A4185c'
);
contractsToProxies.set(
  '0x21CBd7098bf18F293fbF5451Be2Fc968EAA1e072', // AggregatorTesla_3
  '0x1ceDaaB50936881B3e449e47e40A2cDAF5576A4a'
);
contractsToProxies.set(
  '0xBAFe3CB0E563E914806A99D547bdBF2Cfcf5fDF6', // AggregatorSNX_4
  '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'
);
contractsToProxies.set(
  '0x9D6acD34D481512586844fD65328BD358d306752', // AggregatorCOMP_4
  '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'
);
contractsToProxies.set(
  '0x32dCB582EcD6193937BD33168e19173Cfe10a140', // AggregatorBNB_4
  '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A'
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
