/* eslint-disable @typescript-eslint/no-var-requires */
'use strict';

const fs = require('fs');
const path = require('path');
const program = require('commander');
const yamlInput = require('./yaml-inputs');
const { createAggregatorBlock } = require('./helpers');

program
  .command('create-yaml')
  .description('Add rates to yaml files and builds the contractsToProxies code using the mustache templating engine')
  .option('-e, --env <value>', 'defaults to mainnet-ovm, but can be set to kovan-ovm', 'mainnet-ovm')
  .action(async ({ env }) => {
    const contracts = yamlInput[env];
    const newLine = '\n';
    const readOnlyComment = `// this is a read only file generated by mustache/handle-rates.${newLine}`;
    const space = '\xa0';
    const doubleSpace = space + space;
    let contractsToProxiesContent = `${readOnlyComment}export let contractsToProxies = new Map<string, string>();${newLine}`;
    contracts.chainlink.forEach(({ aggregator, proxy, feed }) => {
      if (proxy != null) {
        contractsToProxiesContent += `contractsToProxies.set(${newLine}${doubleSpace}'${aggregator.toLowerCase()}',${space}//${space}${feed}${newLine}${doubleSpace}'${proxy}'${newLine});${newLine}`;
      }
    });
    contractsToProxiesContent += readOnlyComment;
    const targetFile = path.join(__dirname, '../src/', 'contractsToProxies.ts');
    fs.writeFileSync(targetFile, contractsToProxiesContent, 'utf8');
    const chainlinkData = contracts.chainlink.map(createAggregatorBlock);
    const yamlData = { yaml: { ...contracts, chainlinkData } };
    delete yamlData.chainlink;
    return console.log(JSON.stringify(yamlData, null, 2) + '\n');
  });

program.parse(process.argv);
